version: '3' # Версия докер композа (аналогия как в HTML)

services: # Различне сервисы например Фронтенд бекенд (или модули как у нас в проекте)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run start # Запускает dev сервер не prod (хотя этот файл для прода)
    stdin_open: true # Последние 2 поля для работы докера с интерактивной консолью реакта
    tty: true
    volumes: # valumes судя по объяснению доп хранилища для контейнера, за пределами его внутреннего состояния
      - ./frontend/src:/usr/src/app/src # Слева путь к папке src, значит мы хотим нашу папку SIM LINKнуть в папку /usr/src/app/src (В докерфайле это путь к проекту)
  
  api: # Сервис 
    command: npm run dev # Команда которая выполнится при старте сервиса
    volumes: # valumes судя по лбъяснению доп хранилиза для контейнера, за пределами его внутреннего состояния
      - ./api/src:/usr/src/app/src # Слева путь к папке src, значит мы хотим нашу папку SIM LINKнуть в папку /usr/src/app/src (В докерфайле это путь к проекту)
      
  auth: # Сервис 
    command: npm run dev # Команда которая выполнится при старте сервиса
    volumes: # valumes судя по лбъяснению доп хранилиза для контейнера, за пределами его внутреннего состояния
      - ./auth/src:/usr/src/app/src # Слева путь к папке src, значит мы хотим нашу папку SIM LINKнуть в папку /usr/src/app/src (В докерфайле это путь к проекту)
      
  nginx: # Сервис 
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
